import type { components } from "./types/api";

type ProductDto = components["schemas"]["ProductDto"];
type OrderDto = components["schemas"]["OrderDto"];

export const mockProducts: ProductDto[] = [
  {
    id: "prod_1",
    slug: "wireless-headphones",
    name: "Wireless Noise-Canceling Headphones",
    description:
      "High-quality wireless headphones with active noise cancellation.",
    price: { amountMinor: 29900, currency: "USD" },
    stockQuantity: 45,
    status: "ACTIVE",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    sku: "WH-1000XM4",
    categorySlug: "electronics",
    reorderPoint: 10,
    images: { main: "/products/1g.png" },
    colors: ["Black", "Silver"],
    sizes: [],
  },
  {
    id: "prod_2",
    slug: "ergonomic-chair",
    name: "Ergonomic Office Chair",
    description: "Comfortable office chair with lumbar support.",
    price: { amountMinor: 19999, currency: "USD" },
    stockQuantity: 5,
    status: "LOW_STOCK",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    sku: "OC-ERGO-01",
    categorySlug: "furniture",
    reorderPoint: 10,
    images: { main: "/products/3b.png" },
    colors: ["Black", "Grey"],
    sizes: [],
  },
  {
    id: "prod_3",
    slug: "mechanical-keyboard",
    name: "Mechanical Gaming Keyboard",
    description: "RGB mechanical keyboard with cherry MX red switches.",
    price: { amountMinor: 12900, currency: "USD" },
    stockQuantity: 0,
    status: "OUT_OF_STOCK",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    sku: "KB-MECH-RGB",
    categorySlug: "electronics",
    reorderPoint: 20,
    images: { main: "/products/4p.png" },
    colors: ["Black", "White"],
    sizes: [],
  },
];

export const mockOrders: OrderDto[] = [
  {
    id: "ord_1001",
    userId: "usr_1",
    items: [
      {
        productId: "prod_1",
        quantity: 1,
        unitPrice: { amountMinor: 29900, currency: "USD" },
        lineTotal: { amountMinor: 29900, currency: "USD" },
        productName: "Wireless Noise-Canceling Headphones",
      },
    ],
    subtotal: { amountMinor: 29900, currency: "USD" },
    total: { amountMinor: 29900, currency: "USD" },
    shippingAddress: {
      recipientName: "John Doe",
      phone: "+1234567890",
      line1: "123 Main St",
      city: "San Francisco",
      postalCode: "94105",
      countryCode: "US",
    },
    status: "PENDING",
    paymentStatus: "PAID",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    customerName: "John Doe",
    customerEmail: "john@example.com",
  },
  {
    id: "ord_1002",
    userId: "usr_2",
    items: [
      {
        productId: "prod_2",
        quantity: 2,
        unitPrice: { amountMinor: 19999, currency: "USD" },
        lineTotal: { amountMinor: 39998, currency: "USD" },
        productName: "Ergonomic Office Chair",
      },
    ],
    subtotal: { amountMinor: 39998, currency: "USD" },
    total: { amountMinor: 39998, currency: "USD" },
    shippingAddress: {
      recipientName: "Alice Smith",
      phone: "+1987654321",
      line1: "456 Market St",
      city: "New York",
      postalCode: "10001",
      countryCode: "US",
    },
    status: "SHIPPED",
    paymentStatus: "PAID",
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    customerName: "Alice Smith",
    customerEmail: "alice@example.com",
  },
];
